# Form implementation generated from reading ui file 'UI/addEditCoffeeForm.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddEditCoffeeForm(object):
    def setupUi(self, AddEditCoffeeForm):
        AddEditCoffeeForm.setObjectName("AddEditCoffeeForm")
        AddEditCoffeeForm.resize(400, 300)
        self.centralwidget = QtWidgets.QWidget(parent=AddEditCoffeeForm)
        self.centralwidget.setObjectName("centralwidget")
        self.nameEdit = QtWidgets.QLineEdit(parent=AddEditCoffeeForm)
        self.nameEdit.setGeometry(QtCore.QRect(130, 20, 200, 24))
        self.nameEdit.setObjectName("nameEdit")
        self.roastEdit = QtWidgets.QLineEdit(parent=AddEditCoffeeForm)
        self.roastEdit.setGeometry(QtCore.QRect(130, 50, 200, 24))
        self.roastEdit.setObjectName("roastEdit")
        self.groundCheck = QtWidgets.QCheckBox(parent=AddEditCoffeeForm)
        self.groundCheck.setGeometry(QtCore.QRect(130, 80, 100, 20))
        self.groundCheck.setObjectName("groundCheck")
        self.descEdit = QtWidgets.QLineEdit(parent=AddEditCoffeeForm)
        self.descEdit.setGeometry(QtCore.QRect(130, 110, 200, 24))
        self.descEdit.setObjectName("descEdit")
        self.priceSpin = QtWidgets.QDoubleSpinBox(parent=AddEditCoffeeForm)
        self.priceSpin.setGeometry(QtCore.QRect(130, 140, 100, 24))
        self.priceSpin.setMaximum(10000.0)
        self.priceSpin.setObjectName("priceSpin")
        self.volumeSpin = QtWidgets.QSpinBox(parent=AddEditCoffeeForm)
        self.volumeSpin.setGeometry(QtCore.QRect(130, 170, 100, 24))
        self.volumeSpin.setMaximum(10000)
        self.volumeSpin.setObjectName("volumeSpin")
        self.saveBtn = QtWidgets.QPushButton(parent=AddEditCoffeeForm)
        self.saveBtn.setGeometry(QtCore.QRect(150, 220, 100, 30))
        self.saveBtn.setObjectName("saveBtn")

        self.retranslateUi(AddEditCoffeeForm)
        QtCore.QMetaObject.connectSlotsByName(AddEditCoffeeForm)

    def retranslateUi(self, AddEditCoffeeForm):
        _translate = QtCore.QCoreApplication.translate
        AddEditCoffeeForm.setWindowTitle(_translate("AddEditCoffeeForm", "Добавить/Редактировать кофе"))
        self.groundCheck.setText(_translate("AddEditCoffeeForm", "Молотый"))
        self.saveBtn.setText(_translate("AddEditCoffeeForm", "Сохранить"))
